var bingoList = [];
// Summer Forest 1
bingoList[1] = [
  { name: "Win Swordsman from a Foreign Land", types: ["Teana", "Villager 1", "Teana 2nd", "Mountain"] },
  { name: "Win Monster Eye", types: ["Teana", "Villager 1", "Mage Soldier", "Teana 2nd", "Mountain"] },
  { name: "Win Armed Ninja", types: ["Teana", "Villager 1", "Teana 2nd", "Mountain"] },
  { name: "Win Sinister Serpent", types: ["Teana", "Villager 1", "Teana 2nd", "Mountain"] },
  { name: "Win Shadow Specter", types: ["Simon", "Villager 1", "Keith", "Mountain", "Meadow"] },
  { name: "Beat Duel Master K 25 times", types: ["Duel Count", "Duel Master K"] },
  { name: "Fuse Mystical Elf", types: ["Fuse"] },
  { name: "Win Phantom Dewan", types: ["Bakura"] },
  { name: "Win Lucky Trinket", types: ["Bakura"] },
  { name: "Win Wing Egg Elf", types: ["Bakura"] },
  { name: "Win Fiend Refrection #2", types: ["Mai", "Pegasus"] },
  { name: "Win Droll Bird", types: ["Mai", "Pegasus", "Jono 2nd"] },
  { name: "Win Mavelus", types: ["Mai", "Pegasus"] },
  { name: "Win Kurama", types: ["Mai", "Pegasus"] },
  { name: "Fuse Shadow Specter", types: ["Fuse"] },
  { name: "Fuse Blackland Fire Dragon", types: ["Fuse"] },
  { name: "Win 10 Dragons", types: ["Dragon"] },
  { name: "Win Milus Radiant", types: ["Teana", "Villager 1", "Pegasus", "Teana 2nd", "Mountain"] }
];
bingoList[2] = [
  { name: "Win Skull Servant", types: ["Teana", "Villager 1", "Keith", "Teana 2nd", "Mountain"] },
  { name: "Win Kuriboh", types: ["Teana", "Villager 1", "Mage Soldier", "Teana 2nd", "Mountain"] },
  { name: "Win Tomozaurus", types: ["Simon", "Rex", "Jono 2nd"] },
  { name: "Win Weather Control", types: ["Simon", "Bakura", "Jono 2nd", "Meadow"] },
  { name: "Win Mystery Hand", types: ["Simon", "Mage Soldier", "Jono 2nd"] },
  { name: "Beat Simon Muran 25 times", types: ["Duel Count", "Simon"] },
  { name: "Fuse Sword Arm of Dragon", types: ["Fuse"] },
  { name: "Fuse Flame Swordsman", types: ["Fuse"] },
  { name: "Win Secretarian of Secrets", types: ["Bakura", "Jono 2nd"] },
  { name: "Win Ray & Temperature", types: ["Bakura"] },
  { name: "Win Boo Koo", types: ["Bakura", "Jono 2nd"] },
  { name: "Win Griffore", types: ["Mai", "Meadow"] },
  { name: "Win Fiend Kraken", types: ["Mai", "Shadi", "Isis", "Ocean"] },
  { name: "Win Jellyfish", types: ["Mai", "Shadi", "Isis", "Ocean"] },
  { name: "Win Cyber Shield", types: ["Mai", "Isis"] },
  { name: "Fuse Summoned Skull", types: ["Fuse"] },
  { name: "Win 10 Spellcasters", types: ["Spellcaster"] },
  { name: "Win Dark Plant", types: ["Simon", "Villager 1", "Weevil", "Mountain"] }
];
bingoList[3] = [
  { name: "Win Time Wizard", types: ["Simon", "Jono", "Bakura"] },
  { name: "Have 75 Star Chips", types: ["Star Chips"] },
  { name: "Win Change Slime", types: ["Villager 1", "Isis", "Mountain"] },
  { name: "Win Mystic Lamp", types: ["Villager 1", "Bakura", "Mountain"] },
  { name: "Win Ancient Jar", types: ["Teana", "Villager 1", "Teana 2nd", "Mountain"] },
  { name: "Win Dancing Elf", types: ["Teana", "Villager 1", "Bakura", "Teana 2nd"] },
  { name: "Beat Teana 25 times", types: ["Duel Count", "Teana"] },
  { name: "Win Mech Mole Zombie", types: ["Keith", "Jono 2nd"] },
  { name: "Win Phantom Ghost", types: ["Keith"] },
  { name: "Win Air Marmot of Nefariousness", types: ["Pegasus", "Jono 2nd"] },
  { name: "Win Meotoko", types: ["Pegasus"] },
  { name: "Win Solitude", types: ["Pegasus"] },
  { name: "Win Flame Ghost", types: ["Keith"] },
  { name: "Win Holograh", types: ["Keith"] },
  { name: "Fuse The Wicked Worm Beast", types: ["Fuse"] },
  { name: "Fuse Zombie Warrior", types: ["Fuse"] },
  { name: "Win 10 Fiends", types: ["Fiend"] },
  { name: "Win Zone Eater", types: ["Teana", "Villager 1", "Isis", "Teana 2nd", "Mountain"] }
];
bingoList[4] = [
  { name: "Win Leghul", types: ["Villager 1", "Mountain"] },
  { name: "Win Fungi of the Musk", types: ["Villager 1", "Mage Soldier", "Mountain"] },
  { name: "Win Griggle", types: ["Villager 1", "Weevil", "Mountain"] },
  { name: "Win Bone Mouse", types: ["Villager 1", "Mountain"] },
  { name: "Win Pot the Trick", types: ["Villager 1", "Jono 2nd", "Mountain"] },
  { name: "Beat Jono 25 times", types: ["Duel Count", "Jono"] },
  { name: "Fuse Koumori Dragon", types: ["Fuse"] },
  { name: "Win White Magical Hat", types: ["Bakura"] },
  { name: "Win Kamion Wizard", types: ["Bakura", "Mage Soldier"] },
  { name: "Win Necrolancer the Timelord", types: ["Bakura"] },
  { name: "Win Djinn the Watcher of the Wind", types: ["Bakura"] },
  { name: "Win The Bewitching Phantom Thief", types: ["Bakura"] },
  { name: "Win Nemuriko", types: ["Bakura"] },
  { name: "Win Mystical Capture Chain", types: ["Bakura"] },
  { name: "Fuse Judge Man", types: ["Fuse"] },
  { name: "Fuse The Snake Hair", types: ["Fuse"] },
  { name: "Win 10 Fairies", types: ["Fairy"] },
  { name: "Win Bat", types: ["Villager 1", "Keith", "Mountain"] }
];
bingoList[5] = [
  { name: "Win Ooguchi", types: ["Teana", "Villager 1", "Teana 2nd", "Mountain"] },
  { name: "Win Key Mace", types: ["Villager 1", "Bakura", "Mountain"] },
  { name: "Win Ameba", types: ["Villager 1", "Mountain"] },
  { name: "Win Little D", types: ["Rex", "Desert"] },
  { name: "Ritual Summon Millennium Shield", types: ["Ritual"] },
  { name: "Win Yami", types: ["Villager 2", "Keith", "Mage Soldier", "Duel Master K"] },
  { name: "Beat Villager 1 25 times", types: ["Duel Count", "Villager 1"] },
  { name: "Fuse Gaia the Dragon Champion", types: ["Fuse"] },
  { name: "Fuse Curse of Dragon", types: ["Fuse"] },
  { name: "Fuse Celtic Guardian", types: ["Fuse"] },
  { name: "Win Dig Beak", types: ["Pegasus"] },
  { name: "Win Gate Deeg", types: ["Pegasus"] },
  { name: "Win Synchar", types: ["Pegasus"] },
  { name: "Win Torike", types: ["Pegasus", "Meadow"] },
  { name: "Win Wolf", types: ["Pegasus"] },
  { name: "Win Silver Fang", types: ["Pegasus", "Meadow"] },
  { name: "Win Dark Gray", types: ["Pegasus"] },
  { name: "Win Queen's Double", types: ["Villager 1", "Mountain"] }
];
//
bingoList[6] = [
  { name: "Win Wasteland", types: ["Rex", "Keith", "Desert"] },
  { name: "Have 50 cards in Library", types: ["Library"] },
  { name: "Win Mountain", types: ["Rex", "Mai", "Desert"] },
  { name: "Win Gokibore", types: ["Weevil", "Mai"] },
  { name: "Win Killer Needle", types: ["Weevil"] },
  { name: "Win Basic Insect", types: ["Weevil", "Jono 2nd"] },
  { name: "Win Koumori Dragon", types: ["Mai", "Isis", "Kaiba", "Meadow"] },
  { name: "Win The Snake Hair", types: ["Mai", "Keith"] },
  { name: "Win Celtic Guardian", types: ["Mai", "Meadow"] },
  { name: "Win Rogue Doll", types: ["Mai", "Bakura"] },
  { name: "Win Petit Dragon", types: ["Pegasus", "Isis", "Kaiba"] },
  { name: "Win Prevent Rat", types: ["Pegasus", "Mage Soldier"] },
  { name: "Win Mystical Sheep #2", types: ["Pegasus"] },
  { name: "Beat Villager 2 20 times", types: ["Duel Count", "Villager 2"] },
  { name: "Fuse Tiger Axe", types: ["Fuse"] },
  { name: "Fuse Thousand Dragon", types: ["Fuse"] },
  { name: "Win 10 Thunders", types: ["Thunder"] },
  { name: "Win Big Insect", types: ["Weevil", "Mai"] }
];
bingoList[7] = [
  { name: "Win Eradicating Aerosol", types: ["Weevil"] },
  { name: "Win Laser Cannon Armor", types: ["Weevil"] },
  { name: "Win Snakeyashi", types: ["Weevil"] },
  { name: "Win Uraby", types: ["Rex", "Desert"] },
  { name: "Win Crawling Dragon #2", types: ["Rex", "Desert"] },
  { name: "Beat Villager 3 20 times", types: ["Duel Count", "Villager 3"] },
  { name: "Win Graveyard and the Hand of Invitation", types: ["Keith"] },
  { name: "Win The 13th Grave", types: ["Keith"] },
  { name: "Win Amazon of the Seas", types: ["Isis"] },
  { name: "Win Hibikime", types: ["Isis"] },
  { name: "Win Behegon", types: ["Isis"] },
  { name: "Win Fiend's Hand", types: ["Keith", "Jono 2nd"] },
  { name: "Win Blue-Eyed Silver Zombie", types: ["Keith"] },
  { name: "Fuse Kairyu-Shin", types: ["Fuse"] },
  { name: "Fuse Rabid Horseman", types: ["Fuse"] },
  { name: "Fuse Armored Zombie", types: ["Fuse"] },
  { name: "Win 10 Rocks", types: ["Rock"] },
  { name: "Win Man-Eating Plant", types: ["Seto", "Forest"] }
];
bingoList[8] = [
  { name: "Win Insect Armor with Laser Cannon", types: ["Weevil"] },
  { name: "Have 50 cards in Chest", types: ["Chest"] },
  { name: "Win Forest", types: ["Weevil", "Pegasus", "Teana 2nd"] },
  { name: "Win Mushroom Man", types: ["Weevil", "Forest"] },
  { name: "Win Midnight Fiend", types: ["Mage Soldier"] },
  { name: "Win Madjinn Gunn", types: ["Mage Soldier"] },
  { name: "Win The Drdek", types: ["Mage Soldier"] },
  { name: "Win Happy Lover", types: ["Bakura"] },
  { name: "Win Petit Angel", types: ["Bakura"] },
  { name: "Win Hourglass of Life", types: ["Bakura"] },
  { name: "Win Angelwitch", types: ["Bakura"] },
  { name: "Win Two-Headed King Rex", types: ["Rex", "Desert"] },
  { name: "Win Bear Trap", types: ["Rex", "Mage Soldier"] },
  { name: "Beat Seto 20 times", types: ["Duel Count", "Seto"] },
  { name: "Fuse Dragon Zombie", types: ["Fuse"] },
  { name: "Fuse Clown Zombie", types: ["Fuse"] },
  { name: "Win 10 Pyros", types: ["Pyro"] },
  { name: "Win Two-Mouth Darkruler", types: ["Rex", "Desert"] }
];
bingoList[9] = [
  { name: "Win Spiked Snail", types: ["Weevil"] },
  { name: "Win Ganigumo", types: ["Weevil"] },
  { name: "Win Alinsection", types: ["Weevil"] },
  { name: "Win Insect Soldiers of the Sky", types: ["Weevil"] },
  { name: "Win Cockroach Knight", types: ["Weevil"] },
  { name: "Beat Rex Raptor 20 times", types: ["Duel Count", "Rex"] },
  { name: "Win Genin", types: ["Bakura"] },
  { name: "Win Akakieisu", types: ["Bakura"] },
  { name: "Win Root Water", types: ["Isis"] },
  { name: "Win Enchanting Mermaid", types: ["Isis"] },
  { name: "Win Beastking of the Swamps", types: ["Isis"] },
  { name: "Win Ancient Sorcerer", types: ["Bakura"] },
  { name: "Win Lunar Queen Elzaim", types: ["Bakura"] },
  { name: "Fuse Pumpking the King of Ghosts", types: ["Fuse"] },
  { name: "Fuse Battle Warrior", types: ["Fuse"] },
  { name: "Fuse Spirit of the Books", types: ["Fuse"] },
  { name: "Win 10 Plants", types: ["Plant"] },
  { name: "Win Korogashi", types: ["Weevil", "Jono 2nd", "Meadow"] }
];
bingoList[10] = [
  { name: "Win Rainbow Flower", types: ["Weevil", "Jono 2nd"] },
  { name: "Win Man-Eater Bug", types: ["Weevil", "Jono 2nd"] },
  { name: "Ritual Summon Yamadron", types: ["Ritual"] },
  { name: "Win Gale Dogra", types: ["Weevil"] },
  { name: "Win Laughing Flower", types: ["Weevil", "Forest"] },
  { name: "Win Minar", types: ["Weevil"] },
  { name: "Win Abyss Flower", types: ["Weevil", "Jono 2nd", "Forest"] },
  { name: "Win Tentacle Plant", types: ["Weevil", "Jono 2nd", "Forest"] },
  { name: "Win Arlownay", types: ["Weevil"] },
  { name: "Win Winged Cleaver", types: ["Weevil"] },
  { name: "Beat Weevil Underwood 20 times", types: ["Duel Count", "Weevil"] },
  { name: "Fuse Charubin the Fire Knight", types: ["Fuse"] },
  { name: "Fuse Dragon Statue", types: ["Fuse"] },
  { name: "Fuse Lord of the Lamp", types: ["Fuse"] },
  { name: "Win Frenzied Panda", types: ["Pegasus"] },
  { name: "Win One Who Hunts Souls", types: ["Pegasus"] },
  { name: "Win Master & Expert", types: ["Pegasus"] },
  { name: "Win Giant Flea", types: ["Weevil", "Mai"] }
];
// 
bingoList[11] = [
  { name: "Win Tyhone", types: ["Mai"] },
  { name: "Have 125 Star Chips", types: ["Star Chips"] },
  { name: "Win Faith Bird", types: ["Mai"] },
  { name: "Win Skull Red Bird", types: ["Mai"] },
  { name: "Win Niwatori", types: ["Mai", "Pegasus"] },
  { name: "Win Winged Dragon #2", types: ["Mai", "Pegasus"] },
  { name: "Win Electro-Whip", types: ["Mai", "Isis"] },
  { name: "Win Lord of the Lamp", types: ["Mai", "Mage Soldier"] },
  { name: "Win Giga-Tech Wolf", types: ["Mai", "Keith"] },
  { name: "Win Mechanicalchacer", types: ["Mai", "Keith"] },
  { name: "Win Blocker", types: ["Mai", "Keith"] },
  { name: "Win Widespread Ruin", types: ["Pegasus", "Kaiba", "Mage Soldier"] },
  { name: "Win Oscillo Hero #2", types: ["Pegasus"] },
  { name: "Win Hitotsu-me Giant", types: ["Pegasus", "Kaiba"] },
  { name: "Beat Mai Valentine 15 times", types: ["Duel Count", "Mai"] },
  { name: "Fuse Fire Reaper", types: ["Fuse"] },
  { name: "Fuse Firegrass", types: ["Fuse"] },
  { name: "Win 10 Aquas", types: ["Aqua"] },
  { name: "Win Blue-Winged Crown", types: ["Mai"] }
];
bingoList[12] = [
  { name: "Win Armored Zombie", types: ["Keith"] },
  { name: "Win Dragon Zombie", types: ["Keith"] },
  { name: "Win Crass Clown", types: ["Keith", "Mage Soldier"] },
  { name: "Win Shadow Ghoul", types: ["Keith"] },
  { name: "Win Blast Juggler", types: ["Keith"] },
  { name: "Win Cyber-Stein", types: ["Keith", "Jono 2nd"] },
  { name: "Win Cyber Commander", types: ["Keith"] },
  { name: "Win Jinzo #7", types: ["Keith", "Jono 2nd", "Meadow"] },
  { name: "Win Stop Defense", types: ["Keith"] },
  { name: "Win Baby Dragon", types: ["Pegasus", "Isis", "Kaiba"] },
  { name: "Win Mountain Warrior", types: ["Pegasus"] },
  { name: "Win Sleeping Lion", types: ["Pegasus", "Mage Soldier"] },
  { name: "Win Stain Storm", types: ["Keith"] },
  { name: "Beat Bandit Keith 15 times", types: ["Duel Count", "Keith"] },
  { name: "Fuse Tainted Wisdom", types: ["Fuse"] },
  { name: "Fuse Darkfire Dragon", types: ["Fuse"] },
  { name: "Fuse Big Eye", types: ["Fuse"] },
  { name: "Win 10 Sea Serpents", types: ["Sea Serpent"] },
  { name: "Win Clown Zombie", types: ["Keith"] }
];
bingoList[13] = [
  { name: "Win The Melting Red Shadow", types: ["Shadi", "Isis", "Jono 2nd", "Ocean"] },
  { name: "Win Hitodenchak", types: ["Shadi", "Isis", "Ocean"] },
  { name: "Win Water Element", types: ["Shadi", "Isis", "Ocean"] },
  { name: "Win The Furious Sea King", types: ["Shadi", "Isis", "Ocean"] },
  { name: "Win Serpent Marauder", types: ["Shadi", "Ocean"] },
  { name: "Win Psychic Kappa", types: ["Shadi", "Isis", "Ocean"] },
  { name: "Win Zarigun", types: ["Shadi", "Ocean"] },
  { name: "Win Turtle Racoon", types: ["Shadi"] },
  { name: "Win Mechaleon", types: ["Shadi", "Ocean"] },
  { name: "Win Frog the Jam", types: ["Shadi", "Jono 2nd", "Ocean"] },
  { name: "Win Penguin Soldier", types: ["Shadi", "Ocean"] },
  { name: "Win Twin Long Rods #2", types: ["Shadi", "Ocean"] },
  { name: "Win Eternal Draught", types: ["Shadi"] },
  { name: "Fuse Turtle Tiger", types: ["Fuse"] },
  { name: "Fuse Flame Ghost", types: ["Fuse"] },
  { name: "Fuse Wood Remains", types: ["Fuse"] },
  { name: "Beat Shadi 15 times", types: ["Duel Count", "Shadi"] },
  { name: "Win 10 Fish", types: ["Fish"] },
  { name: "Win Twin Long Rods #1", types: ["Shadi", "Isis", "Ocean"] }
];
// 
bingoList[14] = [
  { name: "Win Mystical Elf", types: ["Bakura", "Meadow"] },
  { name: "Win Saggi the Dark Clown", types: ["Bakura", "Kaiba"] },
  { name: "Have 75 cards in Library", types: ["Library"] },
  { name: "Win Goddess with the Third Eye", types: ["Bakura"] },
  { name: "Win Shining Friendship", types: ["Bakura"] },
  { name: "Win Curtain of the Dark Ones", types: ["Bakura", "Jono 2nd"] },
  { name: "Win Flame Manipulator", types: ["Bakura"] },
  { name: "Win Hurricail", types: ["Bakura", "Jono 2nd"] },
  { name: "Win Hoshiningen", types: ["Bakura", "Jono 2nd"] },
  { name: "Win Skelengel", types: ["Bakura"] },
  { name: "Win Lady of Faith", types: ["Bakura"] },
  { name: "Win Yamadron Ritual", types: ["Bakura", "Kaiba"] },
  { name: "Win Book of Secret Arts", types: ["Bakura"] },
  { name: "Win Dark-Piercing Light", types: ["Bakura"] },
  { name: "Beat Yami Bakura 15 times", types: ["Duel Count", "Bakura"] },
  { name: "Fuse Rare Fish", types: ["Fuse"] },
  { name: "Fuse Dissolverock", types: ["Fuse"] },
  { name: "Win 10 Reptiles", types: ["Reptile"] },
  { name: "Win Spirit of the Harp", types: ["Bakura"] }
];
bingoList[15] = [
  { name: "Win Dragon Piper", types: ["Pegasus"] },
  { name: "Win Dragon Capture Jar", types: ["Pegasus", "Kaiba"] },
  { name: "Win Megamorph", types: ["Pegasus"] },
  { name: "Win Bright Castle", types: ["Pegasus", "Kaiba"] },
  { name: "Win Tenderness", types: ["Bakura"] },
  { name: "Win Fusionist", types: ["Pegasus"] },
  { name: "Win One-eyed Shield Dragon", types: ["Pegasus", "Isis", "Kaiba"] },
  { name: "Win Wicked Dragon with the Ersatz Head", types: ["Pegasus", "Isis", "Kaiba"] },
  { name: "Win Burglar", types: ["Pegasus"] },
  { name: "Win Wilmee", types: ["Pegasus"] },
  { name: "Win Little Chimera", types: ["Pegasus", "Jono 2nd"] },
  { name: "Win Obese Marmot of Nefariousness", types: ["Pegasus"] },
  { name: "Win Armored Rat", types: ["Pegasus"] },
  { name: "Win Mystical Sheep #1", types: ["Pegasus"] },
  { name: "Ritual Summon Black Luster Soldier", types: ["Ritual"] },
  { name: "Fuse Enchanting Mermaid", types: ["Fuse"] },
  { name: "Fuse Mavelus", types: ["Fuse"] },
  { name: "Fuse Dragoness the Wicked Knight", types: ["Fuse"] },
  { name: "Beat Pegasus 15 times", types: ["Duel Count", "Pegasus"] }
];
// 
bingoList[16] = [
  { name: "Win Water Magician", types: ["Isis"] },
  { name: "Have 75 cards in Chest", types: ["Chest"] },
  { name: "Win Ice Water", types: ["Isis"] },
  { name: "Beat Isis 10 times", types: ["Duel Count", "Isis"] },
  { name: "Win Darkfire Dragon", types: ["Isis", "Kaiba"] },
  { name: "Win Rare Fish", types: ["Isis"] },
  { name: "Win Wetha", types: ["Isis"] },
  { name: "Win 7 Colored Fish", types: ["Isis"] },
  { name: "Win Ghoul with an Appetite", types: ["Isis"] },
  { name: "Win Fairy of the Fountain", types: ["Isis"] },
  { name: "Win Armored Starfish", types: ["Isis"] },
  { name: "Win Acid Trap Hole", types: ["Pegasus", "Kaiba", "Mage Soldier"] },
  { name: "Win Blackland Fire Dragon", types: ["Pegasus", "Isis", "Kaiba", "Meadow"] },
  { name: "Win The Wicked Worm Beast", types: ["Pegasus", "Kaiba"] },
  { name: "Fuse Legendary Sword", types: ["Fuse"] },
  { name: "Fuse Black Pendant", types: ["Fuse"] },
  { name: "Win 10 Zombies", types: ["Zombie"] },
  { name: "Win Eldeen", types: ["Isis"] }
];
bingoList[17] = [
  { name: "Win Mystic Horseman", types: ["Kaiba"] },
  { name: "Beat Kaiba 10 times", types: ["Duel Count", "Kaiba"] },
  { name: "Win Ryu-Kishin", types: ["Kaiba", "Mage SOldier"] },
  { name: "Win La Jinn the Mystical Genie", types: ["Kaiba", "Mage Soldier"] },
  { name: "Win Sword of Dark Destruction", types: ["Kaiba"] },
  { name: "Win Bad Reaction to Simochi", types: ["Kaiba", "Mage Soldier"] },
  { name: "Win Warrior Elimination", types: ["Kaiba"] },
  { name: "Win Dark Energy", types: ["Kaiba", "Mage Soldier"] },
  { name: "Win Crush Card", types: ["Kaiba"] },
  { name: "Win Curse of Millennium Shield", types: ["Kaiba"] },
  { name: "Win Fake Trap", types: ["Kaiba", "Mage Soldier"] },
  { name: "Win Construct of Mask", types: ["Kaiba"] },
  { name: "Win Puppet Ritual", types: ["Kaiba"] },
  { name: "Fuse Dark Energy", types: ["Fuse"] },
  { name: "Fuse Axe of Despair", types: ["Fuse"] },
  { name: "Fuse Laser Cannon Armor", types: ["Fuse"] },
  { name: "Win 10 Machines", types: ["Machine"] },
  { name: "Win Revival of Skeleton Rider", types: ["Kaiba"] }
];
bingoList[18] = [
  { name: "Win Castle of Dark Illusions", types: ["Mage Soldier"] },
  { name: "Win Barox", types: ["Mage Soldier"] },
  { name: "Beat Mage Soldier 10 times", types: ["Duel Count", "Mage Soldier"] },
  { name: "Win Candle of Fate", types: ["Mage Soldier", "Jono 2nd"] },
  { name: "Win Meda Bat", types: ["Mage Soldier", "Jono 2nd"] },
  { name: "Win Embryonic Beast", types: ["Mage Soldier"] },
  { name: "Win Wicked Mirror", types: ["Mage Soldier"] },
  { name: "Win Versago the Destroyer", types: ["Mage Soldier"] },
  { name: "Win Gorgon Egg", types: ["Mage Soldier"] },
  { name: "Win King Fog", types: ["Mage Soldier"] },
  { name: "Win Bio Plant", types: ["Mage Soldier"] },
  { name: "Win Needle Ball", types: ["Mage Soldier"] },
  { name: "Fuse Insect Armor with Laser Cannon", types: ["Fuse"] },
  { name: "Fuse Horn of the Unicorn", types: ["Fuse"] },
  { name: "Fuse Beast Fangs", types: ["Fuse"] },
  { name: "Win 10 Insects", types: ["Insect"] },
  { name: "Win Wretched Ghost of the Attic", types: ["Mage Soldier", "Jono 2nd", "Meadow"] },
  { name: "Win Hiro's Shadow Scout", types: ["Mage Soldier", "Jono 2nd"] }
];
bingoList[19] = [
  { name: "Beat Jono 2nd 10 times", types: ["Duel Count", "Jono 2nd"] },
  { name: "Have 175 Star Chips", types: ["Star Chips"] },
  { name: "Win Masked Clown", types: ["Jono 2nd"] },
  { name: "Win Eyearmor", types: ["Jono 2nd"] },
  { name: "Win LaLa Li-oon", types: ["Jono 2nd"] },
  { name: "Win Megirus Light", types: ["Mage Soldier"] },
  { name: "Win Hinotama Soul", types: ["Jono 2nd", "Forest"] },
  { name: "Win Kagemusha of the Blue Flame", types: ["Jono 2nd"] },
  { name: "Win Haniwa", types: ["Jono 2nd"] },
  { name: "Win White Dolphin", types: ["Jono 2nd", "Meadow"] },
  { name: "Win Nightmare Scorpion", types: ["Weevil"] },
  { name: "Win Firegrass", types: ["Weevil", "Forest"] },
  { name: "Win Turu-Purun", types: ["Jono 2nd", "Meadow"] },
  { name: "Win Muka Muka", types: ["Jono 2nd", "Meadow"] },
  { name: "Fuse Steel Shell", types: ["Fuse"] },
  { name: "Fuse Elegant Egotist", types: ["Fuse"] },
  { name: "Win 10 Warriors", types: ["Warrior"] },
  { name: "Win Star Boy", types: ["Jono 2nd"] }
];
bingoList[20] = [
  { name: "Beat Teana 2nd 10 times", types: ["Duel Count", "Teana 2nd"] },
  { name: "Ritual Summon Tri-Horned Dragon", types: ["Ritual"] },
  { name: "Fuse Book of Secret Arts", types: ["Fuse"] },
  { name: "Win Bladefly", types: ["Weevil"] },
  { name: "Win Man Eater", types: ["Weevil", "Forest"] },
  { name: "Win Saber Slasher", types: ["Keith"] },
  { name: "Win Machine Attacker", types: ["Keith"] },
  { name: "Win Wood Remains", types: ["Keith"] },
  { name: "Win Metalmorph", types: ["Keith"] },
  { name: "Win Mystical Moon", types: ["Keith"] },
  { name: "Win Feral Imp", types: ["Mai", "Mage Soldier", "Meadow"] },
  { name: "Win Zombie Warrior", types: ["Keith", "Meadow"] },
  { name: "Win Fire Reaper", types: ["Keith", "Jono 2nd"] },
  { name: "Win Yaiba Robo", types: ["Keith"] },
  { name: "Win Mechanical Spider", types: ["Keith", "Jono 2nd"] },
  { name: "Win Shovel Crusher", types: ["Keith"] },
  { name: "Fuse Raise Body Heat", types: ["Fuse"] },
  { name: "Fuse Dragon Capture Jar", types: ["Fuse"] }
];
// 
bingoList[21] = [
  { name: "Win Kairyu-shin", types: ["Ocean"] },
  { name: "Beat Ocean Mage 5 times", types: ["Duel Count", "Ocean"] },
  { name: "Fuse Dark Hole", types: ["Fuse"] },
  { name: "Fuse Raigeki", types: ["Fuse"] },
  { name: "Fuse Hinotama", types: ["Fuse"] },
  { name: "Win 10 Beast-Warriors", types: ["Beast-Warrior"] },
  { name: "Win Battle Ox", types: ["Mai", "Kaiba"] },
  { name: "Win Witty Phantom", types: ["Mage Soldier"] },
  { name: "Win Big Eye", types: ["Mage Soldier"] },
  { name: "Win Dark Prisoner", types: ["Mage Soldier"] },
  { name: "Win Ancient Brain", types: ["Mage Soldier"] },
  { name: "Win Claw Reacher", types: ["Mage Soldier"] },
  { name: "Win Dark Shade", types: ["Mage Soldier"] },
  { name: "Win Beaver Warrior", types: ["Mai", "Meadow"] },
  { name: "Win Karbonala Warrior", types: ["Mai"] },
  { name: "Win Harpie's Feather Duster", types: ["Mai", "Kaiba"] },
  { name: "Win Axe Raider", types: ["Mai"] },
  { name: "Win Turtle Raccoon", types: ["Ocean"] }
];
bingoList[22] = [
  { name: "Beat Forest Mage 5 times", types: ["Duel Count", "Forest"] },
  { name: "Have 100 cards in Library", types: ["Library"] },
  { name: "Win Wings of Wicked Flame", types: ["Forest"] },
  { name: "Fuse Ryu-Kishin Powered", types: ["Fuse"] },
  { name: "Fuse Ushi Oni", types: ["Fuse"] },
  { name: "Win Commencement Dance", types: ["Kaiba"] },
  { name: "Win Yamatano Dragon Scroll", types: ["Pegasus", "Isis", "Kaiba", "Jono 2nd"] },
  { name: "Win Larvas", types: ["Pegasus"] },
  { name: "Win Umi", types: ["Shadi", "Bakura", "Pegasus"] },
  { name: "Win Turtle Tiger", types: ["Isis"] },
  { name: "Win Arma Knight", types: ["Isis"] },
  { name: "Win Penguin Knight", types: ["Isis"] },
  { name: "Win Breath of Light", types: ["Isis"] },
  { name: "Win Hamburger Recipe", types: ["Kaiba"] },
  { name: "Win Novox's Prayer", types: ["Kaiba"] },
  { name: "Win Fire Eye", types: ["Forest"] },
  { name: "Win 10 Beasts", types: ["Beast"] },
  { name: "Win Krokodilus", types: ["Forest"] }
];
bingoList[23] = [
  { name: "Beat Mountain Mage 5 times", types: ["Duel Count", "Mountain"] },
  { name: "Fuse Tatsunootoshigo", types: ["Fuse"] },
  { name: "Fuse Metal Dragon", types: ["Fuse"] },
  { name: "Win 10 Winged Beasts", types: ["Winged Beast"] },
  { name: "Win Dorover", types: ["Isis"] },
  { name: "Win Grappler", types: ["Kaiba"] },
  { name: "Win Terra the Terrible", types: ["Mage Soldier"] },
  { name: "Win Dark Titan of Terror", types: ["Mage Soldier"] },
  { name: "Win Axe of Despair", types: ["Mage Soldier"] },
  { name: "Win Kanikabuto", types: ["Shadi", "Ocean"] },
  { name: "Win Masked Sorcerer", types: ["Bakura"] },
  { name: "Win Binding Chain", types: ["Bakura"] },
  { name: "Win Toad Master", types: ["Isis"] },
  { name: "Win Monsturtle", types: ["Isis"] },
  { name: "Win Horn Imp", types: ["Mage Soldier", "Meadow"] },
  { name: "Win Sogen", types: ["Kaiba", "Meadow"] },
  { name: "Win Goblin Fan", types: ["Kaiba"] },
  { name: "Fuse Giga-Tech Wolf", types: ["Fuse"] }
];
bingoList[24] = [
  { name: "Win Sword Arm of Dragon", types: ["Desert"] },
  { name: "Win Megazowler", types: ["Desert"] },
  { name: "Have 100 cards in Chest", types: ["Chest"] },
  { name: "Win Dark Magician", types: ["Meadow"] },
  { name: "Win Gaia the Fierce Knight", types: ["Meadow"] },
  { name: "Win Trial of Nightmares", types: ["Mage Soldier"] },
  { name: "Win Malevolent Nuzzler", types: ["Mage Soldier"] },
  { name: "Win Machine Conversion Factory", types: ["Mage Soldier"] },
  { name: "Win Invisible Wire", types: ["Mage Soldier"] },
  { name: "Win The Shadow Who Controls the Dark", types: ["Mage Soldier"] },
  { name: "Win Tainted Wisdom", types: ["Mage Soldier"] },
  { name: "Win Lord of Zemia", types: ["Mage Soldier"] },
  { name: "Win Dark King of the Abyss", types: ["Mage Soldier"] },
  { name: "Win Mammoth Graveyard", types: ["Meadow"] },
  { name: "Fuse Cyber Soldier", types: ["Fuse"] },
  { name: "Fuse Dice Armadillo", types: ["Fuse"] },
  { name: "Win 10 Dinosaurs", types: ["Dinosaur"] },
  { name: "Beat Desert Mage 5 times", types: ["Duel Count", "Desert"] }
];
bingoList[25] = [
  { name: "Beat Meadow Mage 5 times", types: ["Duel Count", "Meadow"] },
  { name: "Win Giant Soldier of Stone", types: ["Meadow"] },
  { name: "Win Catapult Turtle", types: ["Meadow"] },
  { name: "Win Legendary Sword", types: ["Meadow"] },
  { name: "Win Curse of Dragon", types: ["Meadow"] },
  { name: "Win Sangan", types: ["Mage Soldier", "Meadow"] },
  { name: "Win Job-Change Mirror", types: ["Mage Soldier"] },
  { name: "Win Horn of Light", types: ["Meadow"] },
  { name: "Win Horn of the Unicorn", types: ["Meadow"] },
  { name: "Win Dark Hole", types: ["Meadow"] },
  { name: "Win Final Flame", types: ["Meadow"] },
  { name: "Win Spellbinding Circle", types: ["Meadow"] },
  { name: "Win House of Adhesive Tape", types: ["Meadow"] },
  { name: "Ritual Summon Serpent Night Dragon", types: ["Ritual"] },
  { name: "Fuse Thunder Dragon", types: ["Fuse"] },
  { name: "Fuse Stone D.", types: ["Fuse"] },
  { name: "Fuse 7 Colored Fish", types: ["Fuse"] },
  { name: "Win Eatgaboon", types: ["Meadow"] }
];

$(function() { srl.bingo(bingoList, 5); });
